name: create private package

on:
  pull_request:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@booseat'
      - run: pnpm install & pnpm -r build
      - run: |
            pnpm \
            --filter @booseat/directus-app \
            --filter @booseat/directus-api \
            --filter @booseat/directus-validation \
            --filter @booseat/directus \
            publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
